### ISSUE TITLE
El botón cerrar sesión no cierra sesión. No podes volver a loguearte con el mismo usuario.

### ISSUE THREAD

**Issue by juanpablopumarega** [Fortran-Unlam/TPA#27]

**Comment by juanpablopumarega** [comment]
Si ya creaste una sala y saliste de la misma para cerrar sesion.

**Comment by pmcruz90** [comment]
Juan, desde que ventana pasa? Pasa antes de iniciar partida o desp de terminar un juego?

**Comment by juanpablopumarega** [comment]
Desde que llegas a una sala y volves al inicio
